# Estadística descriptiva

### Importar librerias

In [11]:
import pandas as pd

### Carga de datos

In [12]:
#cargamos el conjunto de datos ya limpio
df_biare = pd.read_csv("../Limpieza de datos (Practica 1)/biare_limpio_2021_2024.csv")

### Aplicamos estadística descriptiva

#### Preguntras sobre bienestar autorreportado: Satisfacción con la vida en general

In [13]:
# mostramos las estadísticas descriptivas de las preguntas sobre satisfacción con la vida en general
df_biare[["cb_P1", "cb_P2"]].describe()

             cb_P1        cb_P2
count  8019.000000  8019.000000
mean      8.376356     7.951116
std       1.641784     1.932086
min       0.000000     0.000000
25%       8.000000     7.000000
50%       9.000000     8.000000
75%      10.000000     9.000000
max      10.000000    10.000000

#### Preguntras sobre bienestar autorreportado: Eudemonia

In [14]:
# mostramos las estadísticas descriptivas de las preguntas sobre eudemonia
df_biare[["cb_P3_1", "cb_P3_2", "cb_P3_3", "cb_P3_4", "cb_P3_5", "cb_P3_6", "cb_P3_7", "cb_P3_8", "cb_P3_9", "cb_P3_10", "cb_P3_11"]].describe()

,cb_P3_1,cb_P3_2,cb_P3_3,cb_P3_4,cb_P3_5,cb_P3_6,cb_P3_7,cb_P3_8,cb_P3_9,cb_P3_10,cb_P3_11
count,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000
mean,8.746602,8.702332,9.200274,8.877416,9.133807,9.198404,8.913331,9.007108,7.977553,8.668537,4.666168
std,1.500524,1.531431,1.364041,1.430021,1.269567,1.333011,1.500344,1.472649,2.597511,1.533730,3.216813
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,8.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000,7.000000,8.000000,2.000000
50%,9.000000,9.000000,10.000000,9.000000,10.000000,10.000000,10.000000,10.000000,9.000000,9.000000,5.000000
75%,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

#### Preguntras sobre bienestar autorreportado: Balance animico

In [16]:
# mostramos las estadísticas descriptivas de las preguntas sobre balance animico
df_biare[["cb_P4_1", "cb_P4_2", "cb_P4_3", "cb_P4_4", "cb_P4_5", "cb_P4_6", "cb_P4_7", "cb_P4_8", "cb_P4_9", "cb_P4_10"]].describe()

,cb_P4_1,cb_P4_2,cb_P4_3,cb_P4_4,cb_P4_5,cb_P4_6,cb_P4_7,cb_P4_8,cb_P4_9,cb_P4_10
count,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000
mean,7.734131,7.358025,7.202644,7.935653,7.706073,1.518394,1.923307,2.179199,1.281581,1.143160
std,2.129658,2.239220,2.181972,2.078432,2.265773,1.852642,2.070648,2.059767,1.815038,1.889556
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,6.000000,6.000000,7.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,8.000000,8.000000,7.000000,8.000000,8.000000,1.000000,1.000000,2.000000,0.000000,0.000000
75%,10.000000,9.000000,9.000000,10.000000,10.000000,2.000000,3.000000,4.000000,2.000000,2.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

#### Preguntras sobre bienestar autorreportado: Satisfacción con dominios especificos

In [17]:
# mostramos las estadísticas descriptivas de las preguntas sobre satisfaccion con dominios especificos
df_biare[["cb_P5_1", "cb_P5_2", "cb_P5_3", "cb_P5_4", "cb_P5_5", "cb_P5_6", "cb_P5_7", "cb_P5_8", "cb_P5_9", "cb_P5_10", "cb_P5_11", "cb_P5_12"]].describe()

,cb_P5_1,cb_P5_2,cb_P5_3,cb_P5_4,cb_P5_5,cb_P5_6,cb_P5_7,cb_P5_8,cb_P5_9,cb_P5_10,cb_P5_11,cb_P5_12
count,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000
mean,8.343933,8.396683,8.569273,8.729019,8.486719,7.902731,5.421748,8.681881,8.692605,8.062103,7.458785,7.177079
std,1.628791,1.750500,1.430011,1.536622,1.566969,2.140434,2.887550,1.562990,1.581544,2.004518,2.202380,2.358401
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,4.000000,8.000000,8.000000,7.000000,6.000000,6.000000
50%,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,6.000000,9.000000,9.000000,8.000000,8.000000,8.000000
75%,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,10.000000,10.000000,10.000000,9.000000,9.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

#### Preguntras sociodemograficas

In [18]:
# mostramos las estadísticas descriptivas de las preguntas sociodemograficas
df_biare[["cs_EDA", "cs_ING"]].describe()

            cs_EDA         cs_ING
count  8019.000000    3643.000000
mean     46.370246    4801.575350
std      16.941302    6937.460672
min      18.000000      50.000000
25%      32.000000    1500.000000
50%      45.000000    2500.000000
75%      59.000000    5500.000000
max      97.000000  150000.000000

#### Preguntas sobre vivienda

In [19]:
# mostramos las estadísticas descriptivas de las preguntas sobre vivienda
df_biare[["viv_P1", "viv_P3","viv_P4"]].describe()

            viv_P1       viv_P3       viv_P4
count  8019.000000  8019.000000  8019.000000
mean      3.254271     1.022946     3.190922
std       1.737678     0.185459     1.678689
min       1.000000     1.000000     1.000000
25%       2.000000     1.000000     2.000000
50%       3.000000     1.000000     3.000000
75%       4.000000     1.000000     4.000000
max      16.000000     5.000000    16.000000

### Estadistica descriptiva de las variables categoricas

#### Género

In [22]:
# mostramos las estadísticas descriptivas del genero
print(df_biare['cs_SEX'].value_counts())

cs_SEX
Mujer     4443
Hombre    3576
Name: count, dtype: int64

#### Nivel de instrucción

In [23]:
#mostramos las estadísticas descriptivas del nivel educativo
print(df_biare['cs_I_NIV'].value_counts())

cs_I_NIV
Profesional                    2258
Secundaria                     1819
Preparatoria o bachillerato    1692
Primaria                       1184
Carrera técnica                 508
Maestría                        229
Ninguno                         187
Normal                           63
Doctorado                        56
No sabe                          21
Preescolar                        2
Name: count, dtype: int64

#### Estado conyugal

In [24]:
#mostramos las estadísticas descriptivas del estado conyugal
print(df_biare['cs_E_CON'].value_counts())

cs_E_CON
Casado(a)          2966
Soltero(a)         2279
Unión libre        1199
Viudo(a)            660
Separado(a)         529
Divorciado(a)       381
No especificado       5
Name: count, dtype: int64

#### Condición de actividad

In [25]:
#mostramos las estadísticas descriptivas de la condición de actividad
print(df_biare['cs_C_ACT'].value_counts())

cs_C_ACT
Trabajó por lo menos una hora para obtener ingresos    4976
Se dedica a los quehaceres del hogar                   1684
Jubilado(a) o pensionado(a)                             690
Estudiante                                              278
Buscó trabajo                                           150
No trabajó, pero sí tiene trabajo                        61
Otra situación                                           61
Incapacitado(a) permanentemente para trabajar            58
Trabajó sin pago ayudando a un familiar                  34
Espera respuesta a una solicitud de trabajo              23
No especificado                                           4
Name: count, dtype: int64

#### Estados

In [26]:
#mostramos las estadísticas descriptivas de los estados de méxico
print(df_biare['ENT'].value_counts())

ENT
Jalisco                873
Nuevo León             851
Ciudad de México       816
México                 678
Guanajuato             296
Puebla                 217
Veracruz               215
Coahuila               196
Guerrero               179
Colima                 178
Nayarit                178
Oaxaca                 178
Aguascalientes         177
Chiapas                177
Durango                172
Sinaloa                172
Morelos                168
Baja California        167
Querétaro              167
Tamaulipas             167
San Luis Potosí        163
Yucatán                161
Hidalgo                160
Quintana Roo           156
Sonora                 154
Michoacán              152
Chihuahua              149
Tabasco                146
Tlaxcala               142
Baja California Sur    139
Campeche               138
Zacatecas              137
Name: count, dtype: int64

### Agrupación de respuestas

#### Satisfacción de vida por año

In [33]:
#mostramos el promedio de satisfacción con la vida por año
print("Satisfacción con la vida por año")
print(df_biare.groupby('ANIO')['cb_P1'].mean())

Satisfacción con la vida por año
ANIO
2021    8.287456
2022    8.277198
2023    8.343965
2024    8.596798
Name: cb_P1, dtype: float64

#### Satisfacción con la vida por género

In [39]:
#mostramos el promedio de satisfacción con la vida por género
print("\nSatisfacción con la vida por género")
print(df_biare.groupby('cs_SEX')['cb_P1'].mean())

Satisfacción con la vida por sexo
cs_SEX
Hombre    8.477908
Mujer     8.294621
Name: cb_P1, dtype: float64

#### Satiasfacción con la vida por estado

In [35]:
#mostramos el promedio de satisfacción con la vida por estado en México
print("\nSatisfacción con la vida por estado")
print(df_biare.groupby('ENT')['cb_P1'].mean().sort_values(ascending=False))

Satisfacción con la vida por estado
ENT
Aguascalientes         8.971751
Durango                8.819767
Veracruz               8.781395
Puebla                 8.764977
Colima                 8.651685
Nayarit                8.623596
Sonora                 8.610390
Tamaulipas             8.562874
Baja California        8.520958
Chihuahua              8.516779
Nuevo León             8.509988
Hidalgo                8.475000
Coahuila               8.469388
Baja California Sur    8.453237
Sinaloa                8.447674
Guerrero               8.385475
Tabasco                8.369863
Zacatecas              8.364964
México                 8.327434
San Luis Potosí        8.288344
Querétaro              8.287425
Guanajuato             8.280405
Campeche               8.246377
Jalisco                8.215349
Ciudad de México       8.191176
Michoacán              8.164474
Yucatán                8.161491
Chiapas                8.146893
Morelos                8.130952
Quintana Roo           8.121795
Oaxaca                 8.039326
Tlaxcala               7.816901
Name: cb_P1, dtype: float64

#### Satisfacción con la vida por nivel educativo

In [36]:
#mostramos el promedio de satisfacción con la vida por nivel educativo
print("\nSatisfacción con la vida por nivel educativo")
print(df_biare.groupby('cs_I_NIV')['cb_P1'].mean().sort_values(ascending=False))

Satisfacción con la vida por nivel educativo
cs_I_NIV
Maestría                       8.672489
Doctorado                      8.589286
Profesional                    8.562445
Normal                         8.539683
Preparatoria o bachillerato    8.494681
Carrera técnica                8.342520
No sabe                        8.333333
Secundaria                     8.267730
Primaria                       8.030405
Ninguno                        7.962567
Preescolar                     4.500000
Name: cb_P1, dtype: float64

#### Satisfacción con la vida por nivel de actividad

In [37]:
#mostramos el promedio de satisfacción con la vida por nivel de actividad
print("\nSatisfacción con la vida por condición de actividad")
print(df_biare.groupby('cs_C_ACT')['cb_P1'].mean().sort_values(ascending=False))

Satisfacción con la vida por condición de actividad
cs_C_ACT
Estudiante                                             8.683453
Trabajó sin pago ayudando a un familiar                8.676471
Trabajó por lo menos una hora para obtener ingresos    8.447950
Jubilado(a) o pensionado(a)                            8.404348
Se dedica a los quehaceres del hogar                   8.211995
Buscó trabajo                                          8.200000
Espera respuesta a una solicitud de trabajo            8.086957
No trabajó, pero sí tiene trabajo                      8.032787
Otra situación                                         7.278689
No especificado                                        7.250000
Incapacitado(a) permanentemente para trabajar          7.189655
Name: cb_P1, dtype: float64

#### Ingreso promedio por nivel educativo

In [38]:
#mostramos el promedio de ingreso por nivel educativo
print("\nIngreso promedio por nivel educativo")
print(df_biare.groupby('cs_I_NIV')['cs_ING'].mean().sort_values(ascending=False))

Ingreso promedio por nivel educativo
cs_I_NIV
Maestría                       14666.082645
Doctorado                      13824.916667
Profesional                     7695.380952
No sabe                         4799.888889
Carrera técnica                 4475.739583
Preparatoria o bachillerato     3607.103281
Normal                          2658.333333
Secundaria                      2657.030369
Primaria                        1984.192130
Ninguno                         1647.500000
Preescolar                              NaN
Name: cs_ING, dtype: float64

#### Satisfacción con la seguridad del estado

In [41]:
#mostramos el promedio de satisfacción con la seguridad por estado
print("\nSatisfacción con la seguridad por estado")
print(df_biare.groupby('ENT')['cb_P5_7'].mean().sort_values())

Satisfacción con la SEGURIDAD CIUDADANA por estado
ENT
Zacatecas              3.897810
Guerrero               4.156425
San Luis Potosí        4.208589
Morelos                4.398810
Guanajuato             4.533784
México                 4.874631
Quintana Roo           4.897436
Michoacán              4.907895
Ciudad de México       5.006127
Puebla                 5.009217
Jalisco                5.028637
Tabasco                5.061644
Aguascalientes         5.237288
Baja California        5.245509
Tlaxcala               5.281690
Chiapas                5.367232
Colima                 5.376404
Hidalgo                5.406250
Durango                5.424419
Campeche               5.710145
Nuevo León             5.856639
Oaxaca                 5.904494
Sinaloa                6.029070
Sonora                 6.285714
Chihuahua              6.288591
Nayarit                6.544944
Querétaro              6.562874
Tamaulipas             6.586826
Baja California Sur    6.654676
Coahuila               6.974490
Veracruz               7.009302
Yucatán                7.037267
Name: cb_P5_7, dtype: float64

#### Autoestima general por género

In [42]:
#mostramos el promedio de la autoestima general por género
print("\nAutoestima general por género")
print(df_biare.groupby('cs_SEX')['cb_P3_1'].mean())

Autoestima general por género
cs_SEX
Hombre    8.796141
Mujer     8.706730
Name: cb_P3_1, dtype: float64