# Estadística descriptiva

### Importar librerias

In [2]:
import pandas as pd

### Carga de datos

In [5]:
df_biare = pd.read_csv("../Limpieza de datos (Practica 1)/biare_limpio_2021_2024.csv")

### Aplicamos estadística descriptiva

#### Preguntras sobre bienestar autorreportado: Satisfacción con la vida en general

In [12]:
df_biare[["cb_P1", "cb_P2"]].describe()

             cb_P1        cb_P2
count  8019.000000  8019.000000
mean      8.376356     7.951116
std       1.641784     1.932086
min       0.000000     0.000000
25%       8.000000     7.000000
50%       9.000000     8.000000
75%      10.000000     9.000000
max      10.000000    10.000000

#### Preguntras sobre bienestar autorreportado: Eudemonia

In [13]:
df_biare[["cb_P3_1", "cb_P3_2", "cb_P3_3", "cb_P3_4", "cb_P3_5", "cb_P3_6", "cb_P3_7", "cb_P3_8", "cb_P3_9", "cb_P3_10", "cb_P3_11"]].describe()

,cb_P3_1,cb_P3_2,cb_P3_3,cb_P3_4,cb_P3_5,cb_P3_6,cb_P3_7,cb_P3_8,cb_P3_9,cb_P3_10,cb_P3_11
count,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000
mean,8.746602,8.702332,9.200274,8.877416,9.133807,9.198404,8.913331,9.007108,7.977553,8.668537,4.666168
std,1.500524,1.531431,1.364041,1.430021,1.269567,1.333011,1.500344,1.472649,2.597511,1.533730,3.216813
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,8.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000,7.000000,8.000000,2.000000
50%,9.000000,9.000000,10.000000,9.000000,10.000000,10.000000,10.000000,10.000000,9.000000,9.000000,5.000000
75%,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [14]:
df_biare.info()

<class 'pandas.DataFrame'>
RangeIndex: 8019 entries, 0 to 8018
Data columns (total 55 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N_ENT        8019 non-null   int64
 1   ENT          8019 non-null   str
 2   N_REN        8019 non-null   int64
 3   cb_P1        8019 non-null   int64
 4   cb_P2        8019 non-null   int64
 5   cb_P3_1      8019 non-null   int64
 6   cb_P3_2      8019 non-null   int64
 7   cb_P3_3      8019 non-null   int64
 8   cb_P3_4      8019 non-null   int64
 9   cb_P3_5      8019 non-null   int64
 10  cb_P3_6      8019 non-null   int64
 11  cb_P3_7      8019 non-null   int64
 12  cb_P3_8      8019 non-null   int64
 13  cb_P3_9      8019 non-null   int64
 14  cb_P3_10     8019 non-null   int64
 15  cb_P3_11     8019 non-null   int64
 16  cb_P4_1      8019 non-null   int64
 17  cb_P4_2      8019 non-null   int64
 18  cb_P4_3      8019 non-null   int64
 19  cb_P4_4      8019 non-null   int64
 20  cb_P4_5      8019 non-null   int64
 21  cb_P4_6      8019 non-null   int64
 22  cb_P4_7      8019 non-null   int64
 23  cb_P4_8      8019 non-null   int64
 24  cb_P4_9      8019 non-null   int64
 25  cb_P4_10     8019 non-null   int64
 26  cb_P5_1      8019 non-null   int64
 27  cb_P5_2      8019 non-null   int64
 28  cb_P5_3      8019 non-null   int64
 29  cb_P5_4      8019 non-null   int64
 30  cb_P5_5      8019 non-null   int64
 31  cb_P5_6      8019 non-null   int64
 32  cb_P5_7      8019 non-null   int64
 33  cb_P5_8      8019 non-null   int64
 34  cb_P5_9      8019 non-null   int64
 35  cb_P5_10     8019 non-null   int64
 36  cb_P5_11     8019 non-null   int64
 37  cb_P5_12     8019 non-null   int64
 38  cs_SEX       8019 non-null   str
 39  cs_EDA       8019 non-null   int64
 40  cs_ALF       8019 non-null   str
 41  cs_I_NIV     8019 non-null   str
 42  cs_E_CON     8019 non-null   str
 43  cs_C_ACT     8019 non-null   str
 44  cs_OCU       8019 non-null   str
 45  cs_A_ECO     8019 non-null   str
 46  cs_POS       8019 non-null   str
 47  cs_ING       4676 non-null   float64
 48  viv_FCH_PRE  8019 non-null   str
 49  viv_FCH_DEF  8019 non-null   str
 50  viv_P1       8019 non-null   int64
 51  viv_P2       8019 non-null   str
 52  viv_P3       8019 non-null   int64
 53  viv_P4       8019 non-null   int64
 54  ANIO         8019 non-null   int64
dtypes: float64(1), int64(42), str(12)
memory usage: 3.4 MB

#### Preguntras sobre bienestar autorreportado: Balance animico

In [15]:
df_biare[["cb_P4_1", "cb_P4_2", "cb_P4_3", "cb_P4_4", "cb_P4_5", "cb_P4_6", "cb_P4_7", "cb_P4_8", "cb_P4_9", "cb_P4_10"]].describe()

,cb_P4_1,cb_P4_2,cb_P4_3,cb_P4_4,cb_P4_5,cb_P4_6,cb_P4_7,cb_P4_8,cb_P4_9,cb_P4_10
count,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000
mean,7.734131,7.358025,7.202644,7.935653,7.706073,1.518394,1.923307,2.179199,1.281581,1.143160
std,2.129658,2.239220,2.181972,2.078432,2.265773,1.852642,2.070648,2.059767,1.815038,1.889556
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,6.000000,6.000000,7.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,8.000000,8.000000,7.000000,8.000000,8.000000,1.000000,1.000000,2.000000,0.000000,0.000000
75%,10.000000,9.000000,9.000000,10.000000,10.000000,2.000000,3.000000,4.000000,2.000000,2.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

#### Preguntras sobre bienestar autorreportado: Satisfacción con dominios especificos

In [16]:
df_biare[["cb_P5_1", "cb_P5_2", "cb_P5_3", "cb_P5_4", "cb_P5_5", "cb_P5_6", "cb_P5_7", "cb_P5_8", "cb_P5_9", "cb_P5_10", "cb_P5_11", "cb_P5_12"]].describe()

,cb_P5_1,cb_P5_2,cb_P5_3,cb_P5_4,cb_P5_5,cb_P5_6,cb_P5_7,cb_P5_8,cb_P5_9,cb_P5_10,cb_P5_11,cb_P5_12
count,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000
mean,8.343933,8.396683,8.569273,8.729019,8.486719,7.902731,5.421748,8.681881,8.692605,8.062103,7.458785,7.177079
std,1.628791,1.750500,1.430011,1.536622,1.566969,2.140434,2.887550,1.562990,1.581544,2.004518,2.202380,2.358401
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,4.000000,8.000000,8.000000,7.000000,6.000000,6.000000
50%,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,6.000000,9.000000,9.000000,8.000000,8.000000,8.000000
75%,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,10.000000,10.000000,10.000000,9.000000,9.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

#### Preguntras sociodemograficas

In [18]:
df_biare[["cs_EDA", "cs_ING"]].describe()

            cs_EDA         cs_ING
count  8019.000000    4676.000000
mean     46.370246  224655.925150
std      16.941302  412960.656679
min      18.000000      50.000000
25%      32.000000    1800.000000
50%      45.000000    4000.000000
75%      59.000000   18000.000000
max      97.000000  999999.000000

#### Preguntas sobre vivienda

In [19]:
df_biare[["viv_P1", "viv_P3","viv_P4"]].describe()

            viv_P1       viv_P3       viv_P4
count  8019.000000  8019.000000  8019.000000
mean      3.254271     1.022946     3.190922
std       1.737678     0.185459     1.678689
min       1.000000     1.000000     1.000000
25%       2.000000     1.000000     2.000000
50%       3.000000     1.000000     3.000000
75%       4.000000     1.000000     4.000000
max      16.000000     5.000000    16.000000

In [17]:
df_biare.describe()

,N_ENT,N_REN,cb_P1,cb_P2,cb_P3_1,cb_P3_2,cb_P3_3,cb_P3_4,cb_P3_5,cb_P3_6,...,cb_P5_9,cb_P5_10,cb_P5_11,cb_P5_12,cs_EDA,cs_ING,viv_P1,viv_P3,viv_P4,ANIO
count,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,...,8019.000000,8019.000000,8019.000000,8019.000000,8019.000000,4676.000000,8019.000000,8019.000000,8019.000000,8019.000000
mean,3.627260,1.662427,8.376356,7.951116,8.746602,8.702332,9.200274,8.877416,9.133807,9.198404,...,8.692605,8.062103,7.458785,7.177079,46.370246,224655.925150,3.254271,1.022946,3.190922,2022.507170
std,2.501207,0.952422,1.641784,1.932086,1.500524,1.531431,1.364041,1.430021,1.269567,1.333011,...,1.581544,2.004518,2.202380,2.358401,16.941302,412960.656679,1.737678,0.185459,1.678689,1.113442
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,18.000000,50.000000,1.000000,1.000000,1.000000,2021.000000
25%,1.000000,1.000000,8.000000,7.000000,8.000000,8.000000,9.000000,8.000000,9.000000,9.000000,...,8.000000,7.000000,6.000000,6.000000,32.000000,1800.000000,2.000000,1.000000,2.000000,2022.000000
50%,3.000000,1.000000,9.000000,8.000000,9.000000,9.000000,10.000000,9.000000,10.000000,10.000000,...,9.000000,8.000000,8.000000,8.000000,45.000000,4000.000000,3.000000,1.000000,3.000000,2023.000000
75%,6.000000,2.000000,10.000000,9.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,9.000000,9.000000,59.000000,18000.000000,4.000000,1.000000,4.000000,2023.000000
max,8.000000,11.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,97.000000,999999.000000,16.000000,5.000000,16.000000,2024.000000